// <auto-generated />
namespace Agrivolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserState));
        
        string IMigrationMetadata.Id
        {
            get { return "201504262022219_UserState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
