// <auto-generated />
namespace Agrivolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserCity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCity));
        
        string IMigrationMetadata.Id
        {
            get { return "201504262206545_UserCity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
